export interface Item {
    avatar?: string;
    bio?: string;
    email?: string;
    emailVerified?: boolean;
    firstName?: string;
    fullName?: string;
    id: number;
    lastName?: string;
    newKey?: number;
    phone?: string;
    selected?: boolean;
    twitterHandle?: string;
    username?: string;
}

export const data = [
    {
        id: 6,
        fullName: "Lee Bates",
        firstName: "Lee",
        lastName: "Bates",
        username: "lBates",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-004.jpg",
        email: "lBates@example.com",
        emailVerified: true,
        phone: "(780) 990-5935",
        twitterHandle: "lBates",
        bio: "Music ninja. Friend of animals everywhere. Lifelong thinker. Alcohol scholar. Social media expert.",
        newKey: 6,
    },
    {
        id: 7,
        fullName: "Jesus Newman",
        firstName: "Jesus",
        lastName: "Newman",
        username: "jNewman",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-006.jpg",
        email: "jNewman@example.com",
        emailVerified: false,
        phone: "(929) 879-3979",
        twitterHandle: "jNewman",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        newKey: 7,
    },
    {
        id: 8,
        fullName: "Polly Kennedy",
        firstName: "Polly",
        lastName: "Kennedy",
        username: "pKennedy",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-009.jpg",
        email: "pKennedy@example.com",
        emailVerified: false,
        phone: "(359) 870-3834",
        twitterHandle: "pKennedy",
        bio: "Travel lover. Explorer. Analyst. Subtly charming pop culture aficionado. Friendly creator.",
        newKey: 8,
    },
    {
        id: 9,
        fullName: "Augusta Stevenson",
        firstName: "Augusta",
        lastName: "Stevenson",
        username: "aStevenson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-011.jpg",
        email: "aStevenson@example.com",
        emailVerified: true,
        phone: "(844) 425-9035",
        twitterHandle: "aStevenson",
        bio: "Coffee expert. Tv nerd. Proud music fan. Bacon guru. Analyst. Subtly charming gamer.",
        newKey: 9,
    },
    {
        id: 10,
        fullName: "Tyler Perkins",
        firstName: "Tyler",
        lastName: "Perkins",
        username: "tPerkins",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-007.jpg",
        email: "tPerkins@example.com",
        emailVerified: false,
        phone: "(531) 600-3109",
        twitterHandle: "tPerkins",
        bio: "Creator. Unapologetic introvert. Coffee evangelist. Evil music enthusiast. Bacon trailblazer. Troublemaker.",
        newKey: 10,
    },
    {
        id: 11,
        fullName: "Allie Burns",
        firstName: "Allie",
        lastName: "Burns",
        username: "aBurns",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-013.jpg",
        email: "aBurns@example.com",
        emailVerified: false,
        phone: "(876) 848-1948",
        twitterHandle: "aBurns",
        bio: "Travel fanatic. Devoted explorer. Social media maven. Proud analyst. Bacon geek. Zombie ninja. Problem solver. Student. Amateur alcohol practitioner. Thinker.",
    },
    {
        id: 12,
        fullName: "Gordon Murray",
        firstName: "Gordon",
        lastName: "Murray",
        username: "gMurray",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-010.jpg",
        email: "gMurray@example.com",
        emailVerified: true,
        phone: "(251) 681-4876",
        twitterHandle: "gMurray",
        bio: "Music ninja. Friend of animals everywhere. Lifelong thinker. Alcohol scholar. Social media expert.",
    },
    {
        id: 13,
        fullName: "Ronald Casey",
        firstName: "Ronald",
        lastName: "Casey",
        username: "rCasey",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-012.jpg",
        email: "rCasey@example.com",
        emailVerified: true,
        phone: "(584) 532-6828",
        twitterHandle: "rCasey",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
    },
    {
        id: 14,
        fullName: "Rodney Malone",
        firstName: "Rodney",
        lastName: "Malone",
        username: "rMalone",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-014.jpg",
        email: "rMalone@example.com",
        emailVerified: true,
        phone: "(458) 395-9009",
        twitterHandle: "rMalone",
        bio: "Travel lover. Explorer. Analyst. Subtly charming pop culture aficionado. Friendly creator.",
    },
    {
        id: 15,
        fullName: "Louis Sandoval",
        firstName: "Louis",
        lastName: "Sandoval",
        username: "lSandoval",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-016.jpg",
        email: "lSandoval@example.com",
        emailVerified: true,
        phone: "(477) 905-7386",
        twitterHandle: "lSandoval",
        bio: "Coffee expert. Tv nerd. Proud music fan. Bacon guru. Analyst. Subtly charming gamer.",
    },
    {
        id: 16,
        fullName: "Antonio Pierce",
        firstName: "Antonio",
        lastName: "Pierce",
        username: "aPierce",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-017.jpg",
        email: "aPierce@example.com",
        emailVerified: false,
        phone: "(925) 786-5965",
        twitterHandle: "aPierce",
        bio: "Creator. Unapologetic introvert. Coffee evangelist. Evil music enthusiast. Bacon trailblazer. Troublemaker.",
    },
    {
        id: 17,
        fullName: "Joe Myers",
        firstName: "Joe",
        lastName: "Myers",
        username: "jMyers",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-019.jpg",
        email: "jMyers@example.com",
        emailVerified: true,
        phone: "(460) 809-4102",
        twitterHandle: "jMyers",
        bio: "Travel fanatic. Devoted explorer. Social media maven. Proud analyst. Bacon geek. Zombie ninja. Problem solver. Student. Amateur alcohol practitioner. Thinker.",
    },
    {
        id: 18,
        fullName: "Manuel Moss",
        firstName: "Manuel",
        lastName: "Moss",
        username: "mMoss",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-021.jpg",
        email: "mMoss@example.com",
        emailVerified: true,
        phone: "(214) 573-3875",
        twitterHandle: "mMoss",
        bio: "Music ninja. Friend of animals everywhere. Lifelong thinker. Alcohol scholar. Social media expert.",
    },
    {
        id: 19,
        fullName: "George Johnson",
        firstName: "George",
        lastName: "Johnson",
        username: "gJohnson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-023.jpg",
        email: "gJohnson@example.com",
        emailVerified: true,
        phone: "(528) 201-5402",
        twitterHandle: "gJohnson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
    },
    {
        id: 20,
        fullName: "Jose Curry",
        firstName: "Jose",
        lastName: "Curry",
        username: "jCurry",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-025.jpg",
        email: "jCurry@example.com",
        emailVerified: true,
        phone: "(755) 244-1343",
        twitterHandle: "jCurry",
        bio: "Travel lover. Explorer. Analyst. Subtly charming pop culture aficionado. Friendly creator.",
    },
    {
        id: 21,
        fullName: "Elva Brock",
        firstName: "Elva",
        lastName: "Brock",
        username: "eBrock",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-015.jpg",
        email: "eBrock@example.com",
        emailVerified: true,
        phone: "(324) 336-5342",
        twitterHandle: "eBrock",
        bio: "Coffee expert. Tv nerd. Proud music fan. Bacon guru. Analyst. Subtly charming gamer.",
    },
    {
        id: 22,
        fullName: "Mittie Rodriguez",
        firstName: "Mittie",
        lastName: "Rodriguez",
        username: "mRodriguez",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-018.jpg",
        email: "mRodriguez@example.com",
        emailVerified: false,
        phone: "(645) 821-3486",
        twitterHandle: "mRodriguez",
        bio: "Creator. Unapologetic introvert. Coffee evangelist. Evil music enthusiast. Bacon trailblazer. Troublemaker.",
    },
    {
        id: 23,
        fullName: "Dylan Valdez",
        firstName: "Dylan",
        lastName: "Valdez",
        username: "dValdez",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-027.jpg",
        email: "dValdez@example.com",
        emailVerified: true,
        phone: "(269) 551-6325",
        twitterHandle: "dValdez",
        bio: "Travel fanatic. Devoted explorer. Social media maven. Proud analyst. Bacon geek. Zombie ninja. Problem solver. Student. Amateur alcohol practitioner. Thinker.",
    },
    {
        id: 24,
        fullName: "Evelyn Ray",
        firstName: "Evelyn",
        lastName: "Ray",
        username: "eRay",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-018.jpg",
        email: "eRay@example.com",
        emailVerified: false,
        phone: "(230) 628-7334",
        twitterHandle: "eRay",
        bio: "Music ninja. Friend of animals everywhere. Lifelong thinker. Alcohol scholar. Social media expert.",
    },
    {
        id: 25,
        fullName: "Matilda Castillo",
        firstName: "Matilda",
        lastName: "Castillo",
        username: "mCastillo",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-020.jpg",
        email: "mCastillo@example.com",
        emailVerified: true,
        phone: "(571) 357-9739",
        twitterHandle: "mCastillo",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
    },
    {
        "{\n}": "",
        id: 26,
    },
    {
        "{\n ''id': String\n}": "",
        id: 27,
    },
    {
        id: 55,
        fullName: "thana",
        firstName: "ptz",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "thana@business.com",
        emailVerified: true,
        phone: "(581) 400-3514",
        twitterHandle: "-",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
    },
    {
        id: 57,
        fullName: "thana6",
        firstName: "ptz",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "thana@business.com",
        emailVerified: true,
        phone: "(581) 400-3514",
        twitterHandle: "-",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 58,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 59,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 60,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 61,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 62,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 63,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 64,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 65,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 66,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 67,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 68,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 69,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 70,
    },
    {
        fullName: "Susan Williamson",
        firstName: "Susan",
        lastName: "Williamson",
        username: "sWilliamson",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-001.jpg",
        email: "sWilliamson@example.com",
        emailVerified: "true",
        phone: "(581) 400-3514",
        twitterHandle: "sWilliamson",
        bio: "Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.",
        selected: true,
        id: 71,
    },
    {
        fullName: "Lydia Snyder",
        firstName: "Lydia",
        lastName: "Snyder",
        username: "lSnyder",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-008.jpg",
        email: "lSnyder@example.com",
        emailVerified: "false",
        phone: "(201) 703-7735",
        twitterHandle: "lSnyder",
        bio: "Coffee expert. Tv nerd. Proud music fan. Bacon guru. Analyst. Subtly charming gamer.",
        selected: true,
        id: 72,
    },
    {
        fullName: "Henrietta Wagner",
        firstName: "Henrietta",
        lastName: "Wagner",
        username: "hWagner",
        avatar: "https://s3-us-west-1.amazonaws.com/example-data.draftbit.com/people_photos/square/model-005.jpg",
        email: "hWagner@example.com",
        emailVerified: "true",
        phone: "(427) 235-4665",
        twitterHandle: "hWagner",
        bio: "Travel lover. Explorer. Analyst. Subtly charming pop culture aficionado. Friendly creator.",
        selected: true,
        id: 73,
    },
];
